services:
  - type: web
    name: telegram-bot
    env: python
    plan: free   # or starter/pro if you want more resources
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: python yourbot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: POPPLER_PATH
        value: /usr/bin
